import React from "react";
import "@/app/globals.css";

export const metadata = {
    title: "Admin Layout",
    description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
    return (
        <>
            <p>DashboradLayout</p>
            {children}
        </>
    );
};

export default DashboardLayout;
