import React from "react";
import "@/app/globals.css";

export const metadata = {
    title: "Marketing Layout",
    description: "Generated by create next app",
};

const MarketingLayout = ({ children }) => {
    return (
        <>
            <html lang="es">
                <body>
                    <p>MarketingLayout</p>
                    {children}
                </body>
            </html>
        </>
    );
};

export default MarketingLayout;
