import React from "react";
import "@/app/globals.css";

export const metadata = {
    title: "Marketing Layout",
    description: "Generated by create next app",
};

const MarketingLayout = ({ children }) => {
    return (
        <>
            <p>MarketingLayout</p>
            {children}
        </>
    );
};

export default MarketingLayout;
