import React from "react";
import "@/app/globals.css";

export const metadata = {
    title: "Admin Layout",
    description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
    return (
        <>
            <html lang="es">
                <body>
                    <p>DashboradLayout</p>
                    {children}
                </body>
            </html>
        </>
    );
};

export default DashboardLayout;
